### ISSUE TITLE
Help mysql

### ISSUE THREAD

**Issue by TwinMist** [timezone4/eventmanager#33]
Hi, I am wonder if using the eventmanager, would it be possible to pipe the data into mysql?
i am a novice, do you have any more instruction on how to install and setup the application on centos? I know my broadworks details just not sure how to get the app working

many thanks

**Comment by telsgaard** [comment]
Hi TwinMist

Actually this project is very customer specific, and is doing a lot of stuff in order to integrate with Ericsson IMS core for provisioning, but drop me an email about you use case. Getting OCI-R events into mysql is pretty simple.. my email is: thomas.elsgaard@timezone4.com

**Comment by TwinMist** [comment]
Thanks i have emailed you.

**Comment by TwinMist** [comment]
hi, can i ask why have you removed the oci-r script?
